# Generated by Django 5.1.4 on 2024-12-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankloan',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Accountno', models.IntegerField(primary_key='Accountno', serialize=False)),
                ('Startdate', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Mobilenumber', models.IntegerField()),
                ('Amount', models.IntegerField()),
            ],
        ),
    ]
